# Series

In [3]:
import pandas as pd
import numpy as np

In [5]:
L = [1,2,3,4,5]
S = pd.Series(L)


In [6]:
print(L)
print(S)

[1, 2, 3, 4, 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [7]:
type(S)

pandas.core.series.Series

In [8]:
data = [{'a': 1, 'b': 3, 'date': 2013-9-20 },
        {'a': 2, 'b': 6, 'date': 2013-9-20 },
        {'a': 7, 'b': 5, 'date': 2013-9-20 }]

In [9]:
pd.Series(data)

0    {'a': 1, 'b': 3, 'date': 1984}
1    {'a': 2, 'b': 6, 'date': 1984}
2    {'a': 7, 'b': 5, 'date': 1984}
dtype: object

In [10]:
s=[['a','b','c','d'],[1,2,3,4,5]]
s

[['a', 'b', 'c', 'd'], [1, 2, 3, 4, 5]]

In [11]:
pd.Series(s)

0       [a, b, c, d]
1    [1, 2, 3, 4, 5]
dtype: object

In [12]:
s.append("e")
pd.Series(s)

0       [a, b, c, d]
1    [1, 2, 3, 4, 5]
2                  e
dtype: object

In [13]:
snacks = ['pizza','burger','shawarma','franky','sandwitch']
snacks

['pizza', 'burger', 'shawarma', 'franky', 'sandwitch']

In [14]:
pd.Series(snacks)

0        pizza
1       burger
2     shawarma
3       franky
4    sandwitch
dtype: object

In [15]:
days=['Monday','Tuesday','Wednesday','Thursday','Friday']
days

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

In [16]:
s1=pd.Series(data=snacks,index=days)
s1

Monday           pizza
Tuesday         burger
Wednesday     shawarma
Thursday        franky
Friday       sandwitch
dtype: object

In [17]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [18]:
print(a)

[10 20 30 40 50]


In [19]:
pd.Series(a)

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [20]:
dict={'a':10,'b':20,'c':30,'d':40}
dict

{'a': 10, 'b': 20, 'c': 30, 'd': 40}

In [21]:
pd.Series(dict)

a    10
b    20
c    30
d    40
dtype: int64

# Numpy

In [22]:
b =np.array([1,2,3])
b

array([1, 2, 3])

In [23]:
print(b.shape)

(3,)


In [24]:
a=np.array([(1,2,3,4),(4,5,6,7),(1,3,4,6)])
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 3, 4, 6]])

In [25]:
print(a.size)

12


In [26]:
print(a.shape)

(3, 4)


In [27]:
a= a.reshape(4,3)

In [28]:
print(a)

[[1 2 3]
 [4 4 5]
 [6 7 1]
 [3 4 6]]


In [29]:
a=np.array([(1,2,3,4),(4,5,6,7)])

In [30]:
a[1,2] ## Accessing values

6

In [31]:
b=np.array([1,2,3,4])
print(b.sum())

10


In [32]:
a.min()

1

In [33]:
a.max()

7

In [34]:
a.sum()

32

In [35]:
a=np.array([(1,2,3,4),(4,5,6,7)])
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [36]:
a.sum(axis=0)

array([ 5,  7,  9, 11])

In [37]:
a.sum(axis=1)

array([10, 22])

## Duplicates

In [ ]:
dup=pd.DataFrame({'col1':['A','A','B','B','B'],'col2':[2,2,2,3,3]})

In [ ]:
dup

In [ ]:
dup.duplicated()

In [ ]:
dup[dup.duplicated()]

In [ ]:
dup.drop_duplicates()

## Group By

In [ ]:
df = pd.read_csv('Salaries.csv')

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
df.dtypes

In [ ]:
df.tail()

In [ ]:
df.describe()

In [ ]:
df.max()

In [ ]:
df["salary"].max()

In [ ]:
df.mean()

In [ ]:
df.head(3)

In [ ]:
df["rank"].value_counts()

In [ ]:
df.sex.value_counts()

In [ ]:
df["salary"]

In [ ]:
df.describe()

In [ ]:
df[["phd","salary","rank"]].describe(include="all")

In [ ]:
df.phd.count()

In [ ]:
df.phd.mean()

In [ ]:
df.head()

In [ ]:
df.groupby(['rank']).sum()

In [ ]:
df.groupby(['rank','sex','discipline'])[['salary','phd']].mean()

In [ ]:
df[df.salary>120000]

In [ ]:
df.iloc[1:4, 0:3]

In [ ]:
df.iloc[0:10,0:3]

In [ ]:
df.iloc[0:2,]

In [ ]:
df.iloc[:,4]

## Distribution plots

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df1 = pd.read_csv('Universities.csv')

In [ ]:
df1

In [ ]:
plt.hist(df1['Expenses'],bins=20, color='green')

In [ ]:
sns.distplot(df1['Top10'])

In [ ]:
sns.scatterplot(x='SAT',y='Accept',data=df1)

In [ ]:
df1.head(2)

In [ ]:
sns.pairplot(df1)

In [ ]:
df1.skew()

In [ ]:
df1.kurt()

In [ ]:
plt.boxplot(df1["SAT"],vert = False)